from __future__ import annotations


LOG_SCHEMA_VERSION = "1.0"

DEFAULT_WORKFLOW_KEY = "default"

STATUS_SUCCESS = "success"
STATUS_FAILURE = "failure"

STAGE_PROCESSING = "processing"
STAGE_VALIDATION = "validation"
STAGE_OUTPUT = "output"
STAGE_SERVICE = "service"

SERVICE_EVENT_STARTUP = "startup"
SERVICE_EVENT_HEARTBEAT = "heartbeat"
SERVICE_EVENT_SHUTDOWN = "shutdown"

ERROR_RECOVERY_FAILED = "RECOVERY_FAILED"
ERROR_FILE_MISSING = "FILE_MISSING"
ERROR_FILE_LOCKED = "FILE_LOCKED"
ERROR_UNEXPECTED_ERROR = "UNEXPECTED_ERROR"
ERROR_EMPTY_FILE = "EMPTY_FILE"
ERROR_FILE_TOO_LARGE = "FILE_TOO_LARGE"
ERROR_PROCESSING_TIMEOUT = "PROCESSING_TIMEOUT"
ERROR_BARCODE_NOT_FOUND = "BARCODE_NOT_FOUND"
ERROR_INVALID_BARCODE_FORMAT = "INVALID_BARCODE_FORMAT"
ERROR_DUPLICATE_FILE = "DUPLICATE_FILE"
ERROR_UNSUPPORTED_FORMAT = "UNSUPPORTED_FORMAT"
ERROR_CORRUPT_FILE = "CORRUPT_FILE"

ERROR_CODES = frozenset(
    {
        ERROR_RECOVERY_FAILED,
        ERROR_FILE_MISSING,
        ERROR_FILE_LOCKED,
        ERROR_UNEXPECTED_ERROR,
        ERROR_EMPTY_FILE,
        ERROR_FILE_TOO_LARGE,
        ERROR_PROCESSING_TIMEOUT,
        ERROR_BARCODE_NOT_FOUND,
        ERROR_INVALID_BARCODE_FORMAT,
        ERROR_DUPLICATE_FILE,
        ERROR_UNSUPPORTED_FORMAT,
        ERROR_CORRUPT_FILE,
    }
)

LOG_FIELD_SCHEMA_VERSION = "schema_version"
LOG_FIELD_WORKFLOW = "workflow"
LOG_FIELD_HOST = "host"
LOG_FIELD_INSTANCE_ID = "instance_id"
LOG_FIELD_CONFIG_VERSION = "config_version"
LOG_FIELD_ERROR_CODE = "error_code"


def normalize_error_code(reason: str | None) -> str | None:
    if reason is None:
        return None

    normalized = str(reason).strip().upper()
    if not normalized:
        return None
    if normalized in ERROR_CODES:
        return normalized
    return ERROR_UNEXPECTED_ERROR
